# 산포통계

In [2]:
import numpy as np
from scipy import stats
import pandas as pd

### 분산계산

In [3]:
x = [1, 2, 3, 4, 5]
print(np.var(x, ddof = 1)) # 분모 = n - 1 ( 5 - 1), 표본
print(np.array(x).var()) # 분모 = n
# 분모 = n , 자유도(ddof) 0:모분산인경우, 표본분산
print(pd.Series(x).var(ddof = 0))

2.5
2.0
2.0

### 표준편차 계산

In [4]:
x = [1, 2, 3, 4, 5]
print(np.std(x, ddof = 1))
print(np.array(x).std(ddof = 0))
print(pd.Series(x).std(ddof = 1))

1.5811388300841898
1.4142135623730951
1.5811388300841898

### 변동계수의 필요성

- 분산과 표준편차 모두 값의 스케일에 크게 영향을 받아 상대적인 산포를 보여주는데 부적합함.
- 변동계수 = 표준편차 / 평균

In [5]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = x1 * 10

print(np.std(x1, ddof = 1))
print(np.std(x2, ddof = 1))

1.5811388300841898
15.811388300841896

### 스케일링 
- 둘 이상의 변수의 값을 상대적으로 비교할 때 사용

In [6]:
import numpy as np
import pandas as pd

In [7]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = x1 * 10

In [8]:
x1

array([1, 2, 3, 4, 5])

In [9]:
x2

array([10, 20, 30, 40, 50])

In [10]:
# Standard Scaling
z1 = (x1 - x1.mean()) / x1.std()
z2 = (x2 - x2.mean()) / x2.std()

print(z1)
print(z2)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

In [11]:
# Min-max Scaling
z1 = (x1 - x1.min()) / (x1.max() - x1.min())
z2 = (x2 - x2.min()) / (x2.max() - x2.min())

print(z1)
print(z2)

[0.   0.25 0.5  0.75 1.  ]
[0.   0.25 0.5  0.75 1.  ]

In [12]:
# sklearn을 이용한 스케일링을 위한 데이터 준비
X = pd.DataFrame({"X1":[1, 2, 3, 4, 5],
    "X2": [10, 20, 30, 40, 50]})

X

   X1  X2
0   1  10
1   2  20
2   3  30
3   4  40
4   5  50

- 라이브러리 설치 pip install scikit-learn

In [13]:
# scikit learn 의 MinMaxScaler 적용
# 0 ~ 1 데이터 스크케일링함
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() # 인스턴스화
Z = scaler.fit_transform(X) # fit_transform => ndarray
pd.DataFrame(Z, columns=['X1', 'X2'])

     X1    X2
0  0.00  0.00
1  0.25  0.25
2  0.50  0.50
3  0.75  0.75
4  1.00  1.00

In [14]:
# 표준 정규분포에 따라서 데이터의 수준을 맞춤
# 표준 정규분포 : 
from sklearn.preprocessing import StandardScaler

In [15]:
ss_scaler = StandardScaler() # 인스턴스화
Z = ss_scaler.fit_transform(X) # fit_transform => ndarray
pd.DataFrame(Z, columns=['X1', 'X2'])

         X1        X2
0 -1.414214 -1.414214
1 -0.707107 -0.707107
2  0.000000  0.000000
3  0.707107  0.707107
4  1.414214  1.414214

In [16]:
# Standard scaling
from sklearn.preprocessing import StandardScaler

ss_scaler = StandardScaler() # 인스턴스화
S = ss_scaler.fit_transform(X) # fit_transform => ndarray
pd.DataFrame(S, columns=['X1', 'X2'])

         X1        X2
0 -1.414214 -1.414214
1 -0.707107 -0.707107
2  0.000000  0.000000
3  0.707107  0.707107
4  1.414214  1.414214

### 범위와 사분위 범위 계산
- 정규분포(np.random.normal)로 부터 무작위 샘플 만들기
- np.random.normal(0,1,1000) # [정규분포] 평균 0, 표준편차 1, 개수 1000개

In [17]:
# np.random.normal(평균, 편차, size = 갯수)
x = np.random.normal(100, 20, size = 1000)
x

array([105.22395189, 114.43635407, 128.45046027, 142.73875595,
       108.35525814, 110.32410094, 146.2771634 , 124.58292807,
        81.3275295 , 114.96269106, 117.51996444,  88.48166085,
       111.23326811, 120.92381329,  75.11181598,  73.76885752,
        96.14128863,  90.87732666, 104.09948488, 102.49106264,
       121.46810328, 101.52673459,  98.02009849,  84.20840583,
       102.01929449, 117.74417134, 112.98948139, 140.050206  ,
       106.58200327,  73.95431472,  68.20999834,  96.18945665,
        81.55701937,  94.5996288 ,  98.2394296 ,  89.23458235,
       131.17532735, 101.84777232, 106.94143436, 116.01698783,
       139.00182651, 120.13601205, 102.2164391 , 131.94414569,
        86.63188826, 110.12445005, 117.07469616,  97.79177735,
        90.5505472 ,  98.75950066,  95.75550157,  88.70294376,
        97.90968076, 108.9251604 , 111.71452818,  90.35298812,
       126.34583534,  81.68857422,  91.1985481 , 116.13915434,
        82.16099629,  93.63759714, 122.46258138, 103.82649369,
        98.80266835, 109.01309641, 101.79570783, 111.58491044,
        92.85484269, 104.05196896, 113.1254492 , 112.01791569,
       119.76923767,  86.51292369,  90.62517092,  98.21571144,
       126.1364662 , 107.25194071,  96.81894306, 103.29520082,
       116.20985255,  90.45020001,  90.06210877, 123.51752506,
        84.63819773, 121.02185484,  81.48771417,  80.77366134,
       101.3729584 , 111.12021671,  62.85415189,  93.09259074,
       101.8837066 ,  81.17110476, 107.00926424, 104.40047633,
        87.2502532 ,  92.38917613, 109.71303722,  87.05744525,
       109.79467649, 104.79202564,  97.55495952, 104.84805423,
        58.90066008, 115.06248625,  79.37642006, 147.17130012,
        88.02630489,  88.39782927, 127.41779141, 126.80749308,
        99.90344231, 115.75454058,  56.51898532,  76.85953926,
       115.75903195, 121.77470308, 117.84515213, 100.29813984,
        74.09801019,  69.42148941, 103.96258916,  99.17800394,
        56.6406465 , 105.58419828,  91.43213603, 107.30762685,
       116.04909472,  95.31412583, 141.57776045,  92.1584905 ,
        98.79888201, 108.83920633, 106.2187412 ,  71.63529132,
       121.58847876,  94.17321198,  62.15420942,  99.36106036,
        84.5695269 ,  90.78310662, 108.45001983,  78.41161303,
        92.55599696,  63.22379822, 105.87562621, 132.30181967,
        71.21626842,  61.47064626, 107.07467669, 150.79740734,
       130.20905558,  96.87772067,  91.86712992,  99.65834501,
       126.14607392, 115.46894042, 100.0330384 ,  85.13793482,
        85.4745527 , 121.44144083,  85.38007689,  95.6157516 ,
        94.58877152,  98.80760219,  98.88828818, 115.68498649,
        60.78006809, 115.46038098,  75.1932113 ,  93.9138405 ,
       102.95084682,  75.84083397,  93.32182407,  91.68962023,
        98.00025995,  89.30595745,  80.62897974, 136.46059194,
       100.6071673 , 107.83043335,  59.15724698, 105.18588351,
       114.37363471, 113.20734106, 111.39215437, 117.63301299,
        81.17552234,  98.6337265 , 106.94141366, 123.47171137,
       107.90846251, 181.97644048,  89.70899682, 111.06589948,
        89.34182302, 102.89743701,  85.26704165, 103.25582053,
       141.95705988,  84.57949188, 114.3883452 , 114.22772746,
       108.81154305, 108.20094521,  96.59320634,  55.81286445,
        93.11642178,  89.17991223,  70.69582324,  87.87393314,
        68.1430057 , 112.71769131, 108.48910686, 104.03099823,
        83.28385713, 111.63745103, 103.58454501, 120.9104951 ,
        89.96290865,  80.9785546 , 120.85275997, 108.64829895,
       124.22537378, 126.7132141 ,  79.77763361,  80.16685038,
       103.01894177,  79.44687295, 103.91075317,  82.00514459,
       101.29358152,  71.456958  , 101.99907055,  69.47035589,
        72.12717003, 123.40088862,  99.40935229,  89.72128726,
        79.90867128,  84.12947772, 105.67685899,  89.32480719,
        94.99578044,  82.61472859, 136.49492934, 140.93592686,
       112.02870165,  86.61318044, 134.0617144 , 111.90238728,
        40.95841853,  91.77808528,  78.762695  , 116.22564865,
       131.62778839, 104.16572888, 124.28177058, 134.01603687,
       109.73577301,  98.54843975,  91.14823834,  97.01498885,
        97.35804388, 156.75978863, 127.07879462, 121.52640557,
       108.78549781,  85.47930724, 114.32128428,  97.26057043,
       129.88841445,  88.49309167,  99.0481187 , 108.02793727,
       116.40617559, 100.4239484 ,  94.38487325,  96.7928712 ,
        91.75883516,  72.57915558,  93.65577919,  85.56609087,
       117.77981086, 139.11726161, 100.94721795, 108.48226236,
        79.01878835, 109.92581408, 103.45751297, 100.16390409,
       130.28848313,  85.71240949,  87.62559046,  74.85731019,
        99.17889719,  74.09104   ,  50.42657451, 133.13025756,
       117.67811585,  75.72361233,  99.86089508,  81.43682093,
       145.44395317, 139.8441293 ,  92.33519188,  70.50961713,
       110.87331116, 122.14783861,  95.37664839, 112.81103966,
       124.89176081,  75.67624784, 122.55323184,  55.88259489,
       108.89851114, 122.64998529,  95.60350016,  95.79477743,
        80.00941826, 118.45195199,  95.27169167,  96.85865521,
        77.52992442, 103.31878346, 102.77555649,  75.17702063,
        58.81272705,  97.49709054,  79.01587739,  90.92996395,
        91.37856294, 116.22114023,  95.69224314,  94.48985016,
        93.75644677, 102.70616816, 136.38497393,  91.52207721,
       137.42404007,  91.7213672 ,  96.86817206,  91.27764281,
        98.57054738,  94.4404313 , 106.18227106,  53.89962942,
        85.49980718, 112.99048148, 125.42223566,  98.89495816,
       115.66011603,  97.92998133, 134.34016049,  70.75703599,
       147.63847314,  77.9066825 ,  93.64397749, 128.97984902,
       107.47829482,  82.69083179,  99.49268125,  90.79656334,
       109.05268668, 124.12479589, 104.66277368, 101.50416068,
       133.21830475,  94.32021606, 105.03567395, 105.53857043,
       105.1771177 , 132.99712153, 105.92056328, 100.79714457,
        88.16831983,  97.98209554,  92.88515415,  84.6471104 ,
       120.50522691,  62.23057233, 100.00058829, 141.25693951,
        76.90993351,  84.81679662, 126.21855963,  81.93843447,
       129.45840513,  95.73489378,  82.33568002,  92.3500941 ,
        79.51580914,  62.15957664, 108.98129827,  83.37310567,
        63.41509863, 104.07012574,  91.93146471, 105.22829254,
        75.61749157,  90.24180956,  92.89468234, 100.56466194,
       119.02140648, 107.88104734, 130.21667804, 106.70208639,
       130.17816018,  92.51000907, 115.06186369, 134.54169364,
       101.40175813,  87.3116928 , 110.29743015,  92.53379381,
        60.97618732,  85.87551319, 118.13912201,  81.67307889,
       120.90719176, 119.03288615, 104.42222683,  95.11749545,
        83.72874229, 163.89347248,  95.32181936,  81.39964442,
       105.25289322,  91.33579896, 129.10566667,  91.3968183 ,
       116.74134078,  65.98608396,  87.17885929,  59.96731841,
       130.28691718, 104.874312  ,  50.13056243, 132.50660877,
       124.21344255,  76.51421074, 122.2682444 , 116.11473644,
       100.64389626,  94.07146167,  48.80852028, 121.48875174,
       111.73043798, 128.89131019, 104.07447156,  72.95320627,
        92.05063639, 103.58720292,  78.21842035, 114.6966018 ,
       119.96961219, 126.8169841 , 102.73013183, 142.09126799,
        95.36668812,  71.79184545,  76.52922342,  99.28647349,
       112.28321375, 123.62654871, 100.56205346,  87.83617663,
       124.34003001,  73.83486096,  76.98070471, 111.82083809,
       111.91660713, 133.21619573, 107.86903344,  82.30534539,
       115.7673478 , 102.30006575, 113.89207936, 109.34328024,
        68.06055002, 146.61715877, 116.37159915,  71.42837711,
        73.53448665, 114.12538751, 111.79018909, 111.65626794,
       124.74631741,  86.48652594,  77.64052313,  74.91480352,
       110.19232677, 142.48238893, 125.05580622, 112.37868485,
        89.73435828, 111.95863218,  81.37240288, 134.51567633,
        88.76068413, 130.89757622,  71.78376514,  89.75468348,
        80.42604762,  88.36793425,  79.8343243 ,  81.70953871,
       117.56531157, 111.42520898,  95.64207913, 123.35524713,
       127.39926812, 131.84267348,  59.06553903,  45.6803761 ,
        83.33000359,  79.98389823,  98.56104222, 124.87122081,
       103.93455357, 110.36788204, 103.21835961, 115.77186797,
        94.33354855,  89.12357315, 119.96902936,  94.54546623,
       111.14092904, 111.38165961,  84.6644372 ,  91.5651688 ,
        97.9635267 ,  77.18863149, 126.64458793,  65.29868901,
        87.08966635,  81.58889402, 106.88155269,  70.24061772,
       112.811271  ,  84.02294967,  81.69105258,  57.97300528,
        94.41960578, 117.05701445, 113.71086054,  85.2037839 ,
        89.8507164 ,  98.57048202,  97.51385861,  88.9422188 ,
        96.44274893,  86.94217989, 119.38782936, 101.04984906,
        66.251826  ,  88.58089767,  87.3513255 ,  85.93654828,
       104.17961971,  99.46794655, 108.78870853, 119.84423308,
       111.56393905, 101.79251234,  73.76395997,  94.20035011,
       101.29702833,  94.11995215,  75.23160621, 107.28083067,
        99.22152275,  87.4369393 , 126.85198739,  78.24863705,
        95.29146305, 122.74845052, 133.0660451 , 103.77406072,
       102.96090141, 112.13562455, 127.40977835,  76.13560249,
        84.35371271, 100.45366406,  75.15283326,  74.47240876,
       117.72456236, 108.9817014 , 104.6216415 ,  98.35200954,
        62.49306663, 106.79314197, 105.56939517,  78.00321344,
        85.50765321,  97.0097394 , 124.53874688, 104.82621739,
        85.96214248, 112.91025283,  80.53503858,  96.56803595,
        92.41091214,  84.39111593, 115.33780936,  97.38949838,
        71.6214346 , 100.14646221,  96.17712903,  87.67552725,
        59.87256419,  52.83061583, 112.97668565, 109.09402523,
       108.51683205,  77.2178071 , 130.68108835, 107.03089755,
        79.86035681,  87.51651455,  97.9233802 , 106.17196856,
        85.22461141, 100.26958829, 145.08435463,  55.68240927,
       142.25228758,  76.45394248, 108.86220069,  97.42071249,
        78.57867837, 120.46639915,  98.65702126,  84.15952928,
       106.94953761, 110.7279243 , 114.63576224,  95.96299889,
        83.01007031, 124.33725295, 112.76904399,  85.50982669,
        93.56834161, 102.01472639, 115.15002816, 122.08725754,
        96.92073043, 108.74221744, 113.9055693 , 104.80971663,
       105.96957441,  84.31760071, 107.44350223, 101.3351765 ,
        88.70624632,  95.1514903 , 100.06470773, 109.61335207,
       106.62559635,  79.78313359,  76.17770731, 114.62562077,
        99.21641894,  88.93275589, 105.78701094, 115.08040733,
       127.31441319, 105.49407048,  87.66640981, 120.88410119,
        60.75981273, 135.41275964,  98.46623151, 107.89882528,
       110.97249959,  91.13039137,  98.90088916, 102.60620931,
       100.3017283 , 106.65466386, 119.16761043,  99.37909455,
        95.54637399,  83.80904128,  98.94553485, 118.53699854,
        66.69214548,  86.89694009,  55.79879812, 131.45355914,
        81.33184998,  96.26021389,  57.93770837, 102.81976598,
        96.17731861,  76.93478639,  92.15414055, 109.70529754,
        86.37617672, 127.50094321, 114.23080728, 115.17161358,
        99.86564392, 104.29510116,  71.64293835, 139.48072604,
       122.36109578,  66.95760979, 105.34379299, 105.43758365,
       111.18344943,  76.41902802,  98.49192552,  87.46178215,
        91.62852352, 109.66932992, 110.2312191 , 100.76585036,
        73.94232702, 111.49398563,  92.51629681, 110.08198219,
        81.3327496 ,  77.86160999, 116.88318969, 146.7691859 ,
       116.30572626,  86.37268808,  84.36193933, 109.76579536,
       124.84377413,  87.6523537 , 104.74943332, 103.71000529,
       138.90766762,  96.35730148,  92.36436139,  77.9660121 ,
       106.86309929, 116.06903491,  83.3991194 , 118.79026349,
        73.40250105,  67.10678437, 104.98293623,  51.71491498,
       125.11170873,  72.79067686, 112.35272773, 122.65090362,
       106.49821187,  78.60130359, 101.56190222, 100.06844944,
        93.55420344,  75.9578786 ,  93.5775302 ,  90.58715887,
        86.23739747, 127.00973435, 114.59671226,  84.1020472 ,
        67.81908217,  96.95665267,  72.85073227,  98.40553521,
        92.32287646, 110.25709166, 104.49540249, 117.85522608,
        91.98963931, 106.81074127, 115.19477042,  83.23915761,
        77.42350499,  77.2548865 ,  62.32209534,  95.61670991,
        92.53563635,  76.87740131, 124.75798058, 139.07297751,
        92.11326555, 123.69409953, 107.98075713, 103.82085243,
       134.97283363,  92.34454932,  68.01299388, 111.74878842,
       121.47386179,  86.38779737, 111.02630069, 141.74716805,
        72.85116817,  98.94366859, 108.82622554, 107.83898433,
       113.0026615 ,  89.60364425,  67.51079191, 118.15506238,
       110.31140077, 106.83977464, 102.85187079,  78.91956134,
        67.17713989, 116.45928577, 109.15618868,  90.77160631,
        87.75543074, 102.22546382,  83.15378568, 110.03729013,
        54.58117304,  92.19471684,  93.75862791, 104.13798223,
        80.42089898,  69.03518641,  42.83887234,  94.42338759,
       107.91562613, 129.47698325,  72.98337607,  74.48265922,
        93.2684896 , 115.34389869,  87.97648911, 123.61773088,
       114.49939262,  97.16867432,  73.23906659, 123.2910585 ,
        75.67336825, 121.25420141,  71.28537645, 121.82348874,
       116.68283517, 112.54425069, 104.64205909, 110.44949368,
        64.63245032, 109.18328705, 125.7600336 , 121.62829215,
       123.36968915,  92.06983501,  56.58217557, 110.47660989,
        85.7814872 , 103.00142507, 129.66660199, 111.04630744,
        98.42147185,  90.29638478, 111.38588073, 115.06977387,
       111.17710614,  96.30217468,  95.02147284,  77.18641261,
        82.96590952, 125.9828586 ,  98.6609878 ,  84.21276863,
       103.12154177, 122.61255094,  96.83205316,  92.28178624,
        94.44821757, 137.38665714,  81.84573024, 111.08868871,
       101.28645687, 137.11886138,  69.66817854, 106.97303201,
        75.20138563,  80.08874357,  62.06360097, 120.38124681,
       138.19559299,  94.29248458, 136.79798742,  92.58554252,
        55.87366898, 114.88157349,  65.78493942,  99.71246001,
       169.48720925,  84.46109051,  82.81369127, 106.72005835,
        94.82498786, 118.60961024, 109.48491622,  97.63854156,
       101.45417688, 140.91802812,  88.36785709, 106.17812572,
       123.14941932, 117.91972806,  86.66885645,  72.79537863,
        71.67428544, 116.64264853, 104.20835586,  91.13881625,
        65.22057161,  92.1752009 ,  87.56435633,  99.32085725,
       105.62879241,  83.72126828, 101.99344866, 101.54482645,
       101.78561377,  84.38646593,  63.96413726,  80.37062075,
        67.82776342, 119.05246285,  96.7635509 ,  98.17417117,
        86.92871148,  78.57761986,  93.27301557,  78.04981312,
       113.13670268,  86.18098469, 108.74311214,  96.34606016,
       114.41147365,  97.77368992, 101.45092919, 101.44404824,
        65.2310531 , 116.66266997,  95.61102569, 139.57596702,
       104.9518773 ,  85.56357642,  63.44567169, 101.84730356,
        80.98417204, 124.16948962, 100.84394148, 137.22206262,
        94.84764856,  89.93575637,  93.20317727,  89.31853898,
        94.06769884,  92.5719545 ,  60.37047474, 113.57162001,
       122.12094067,  78.63022696,  80.0504804 ,  81.61140607,
       106.68330291, 108.30970582,  80.82577629,  82.67504626,
        63.81264228, 116.39543854,  94.04968554,  62.72577086,
       108.83812525, 102.34283461,  68.02871183, 121.99298299,
        99.03399001,  86.17942512, 106.4974591 ,  90.14023087,
       111.37986984, 101.85758669,  68.70140418,  77.3844575 ,
       123.97663139,  71.28039146,  71.11444918, 112.71074883,
       102.21816533,  88.2872493 ,  97.84778002,  85.33432762,
        94.19619811, 107.76501716,  96.93514349,  90.62759879,
        72.03964333,  74.36825868,  88.24303339,  88.58544163])

In [18]:
print(np.ptp(x))
print(np.max(x) - np.min(x))

141.01802195289284
141.01802195289284

In [19]:
print(np.quantile(x, 0.75) - np.quantile(x, 0.25))
print(stats.iqr(x))

25.930327911493038
25.930327911493038